#!/bin/bash

# 루트 디렉토리로 이동
cd "$(git rev-parse --show-toplevel)"

# Maven Checkstyle 검사 실행
mvn checkstyle:check

# 검사 결과 확인
if [ $? -ne 0 ]; then
    echo "❌ error: Code format is invalid — commit blocked!"
    exit 1
fi